;==================== INCLUDE =======================
INCLUDE		windows.inc
INCLUDE		user32.inc
INCLUDE		kernel32.inc
INCLUDE		gdi32.inc
INCLUDE		winmm.inc
INCLUDE		gdiplus.inc
INCLUDE		ole32.inc
INCLUDE		comdlg32.inc

INCLUDELIB	winmm.lib
INCLUDELIB	gdi32.lib
INCLUDELIB	user32.lib
INCLUDELIB	kernel32.lib
INCLUDELIB	gdiplus.lib
INCLUDELIB	ole32.lib
INCLUDELIB	msvcrt.lib
INCLUDELIB	comdlg32.lib